#!/bin/bash
#SBATCH --mem=64G
#SBATCH --ntasks-per-node=8
#SBATCH --nodes=1


#SBATCH -J 1EEZSolvation # Job Name
#SBATCH -o Solv_output.%j # Output file name (%j expands to jobID)
#SBATCH -e Solv_out.%j # Error file name (%j expands to jobid)
#SBATCH -t 48:00:00 # Run time (hh:mm:ss) - 1.5 hours; do 48 h as default


# make sure we have the module loaded:
module load GROMACS
module list

# timestamps are helpful
echo "job started on $(date)"

# now run gromacs:

bash solvation_shell_COM.sh


echo "job finished on $(date)"



