#!/bin/bash
#SBATCH --mem=100G
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --partition=wsu_gen_gpu.q
#SBATCH --gres=gpu:1


#SBATCH -J hbond # Job Name
#SBATCH -o hbond_outpu.%j # Output file name (%j expands to jobID)
#SBATCH -e hbond_info.%j # Error file name (%j expands to jobid)
#SBATCH -t 72:00:00 # Run time (hh:mm:ss) - 1.5 hours; do 48 h as default

#SBATCH --mail-type=ALL
#SBATCH --mail-user=mheikes.chem@gmail.com

# make sure we have the module loaded:
module load GROMACS
module list

# timestamps are helpful
echo "job started on $(date)"

# now run Gaussian:

bash run_hbonding.sh


echo "job finished on $(date)"



